apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccountName }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: gcp-wi-demo
    {{- include "gcp-wi-app.labels" . | nindent 4 }}